AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: mackerel-cloudwatch-forwarder v__VERSION__ forwards metrics in AWS CloudWatch to the Mackerel.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mackerel-cloudwatch-forwarder
    Description: Forward metrics in AWS CloudWatch to the Mackerel.
    Author: Shogo Ichinose
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["tests"]
    HomePageUrl: https://github.com/shogo82148/mackerel-cloudwatch-forwarder
    SemanticVersion: __VERSION__
    SourceCodeUrl: https://github.com/shogo82148/mackerel-cloudwatch-forwarder

Parameters:
  ParameterName:
    Type: AWS::SSM::Parameter::Name
    Description: Name of SSM Parameter Store Parameter for the Mackerel API Key.
  ForwardSettings:
    Type: String
    Default: "[]"
    Description: Metrics settings for forwarding
  LogLevel:
    Type: String
    Default: warning
    AllowedValues: [panic, fatal, error, warn, warning, info, debug, trace]
    Description: log level(panic, fatal, error, warn, warning, info, debug, trace)
  BaseUrl:
    Type: String
    Default: "https://api.mackerelio.com/"
    Description: base url for the Mackerel API

Resources:
  Forwarder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mackerel-cloudwatch-forwarder
      Runtime: provided.al2
      Timeout: 60
      CodeUri: release/latest/mackerel-cloudwatch-forwarder.zip
      Policies:
        - CloudWatchReadOnlyAccess
        - SSMParameterReadPolicy:
            # HACK: trim "/" prefix. See https://github.com/aws/serverless-application-model/issues/1112
            ParameterName: !Join ["", !Split ["^/", !Sub "^${ParameterName}"]]
      Environment:
        Variables:
          MACKEREL_APIKEY_PARAMETER: !Ref ParameterName
          MACKEREL_APIKEY_WITH_DECRYPT: "1"
          MACKEREL_APIURL: !Ref BaseUrl
          FORWARD_LOG_LEVEL: !Ref LogLevel
      Events:
        ForwardSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: !Ref ForwardSettings
