AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Forward the metrics in AWS CloudWatch to the Mackerel.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mackerel-cloudwatch-forwarder
    Description: Forward the metrics in AWS CloudWatch to the Mackerel.
    Author: Shogo Ichinose
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['tests']
    HomePageUrl: https://github.com/shogo82148/mackerel-cloudwatch-forwarder
    SemanticVersion: 0.0.5
    SourceCodeUrl: https://github.com/shogo82148/mackerel-cloudwatch-forwarder

Parameters: 
  ParameterName: 
    Type: AWS::SSM::Parameter::Name
    Description: Name of SSM Parameter Store Paramer for the Mackerel API Key.
  ForwardSettings:
    Type: String
    Default: '{"service_metrics":[], "host_metrics":[]}'
    Description: Metrics settings for forwarding
  LogLevel:
    Type: String
    Default: warning
    AllowedValues: [panic, fatal, error, warn, warning, info, debug, trace]
    Description: log level(panic, fatal, error, warn, warning, info, debug, trace)
  BaseUrl:
    Type: String
    Default: "https://api.mackerelio.com/"
    Description: base url for the Mackerel API

Resources:
  Forwarder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mackerel-cloudwatch-forwarder
      Runtime: go1.x
      Timeout: 60
      CodeUri: release/latest/mackerel-cloudwatch-forwarder.zip
      Policies:
        - AWSLambdaExecute
        - CloudWatchReadOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ParameterName}"
                - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterName}"
      Environment:
        Variables:
          MACKEREL_APIKEY_PARAMETER: !Ref ParameterName
          MACKEREL_APIKEY_WITH_DECRYPT: 1
          MACKEREL_APIURL: !Ref BaseUrl
          FORWARD_LOG_LEVEL: !Ref LogLevel
      Events:
        ForwardSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: !Ref ForwardSettings
