name: Test
on: [push, pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: go mod download

      - name: Test
        run: go test -race -v -coverprofile=profile.cov ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
